site_name: Delphix Hyperscale Compliance Documentation
site_url: https://www.hyperscale-compliance.delphix.com/
site_description: Documentation for the Delphix Hyperscale Compliance feature.
site_author: Delphix

theme:
  name: material
  custom_dir: overrides
  palette:
    primary:
    accent: light blue
  logo: 'images/delphix-logo-white.png'
  favicon: 'images/logo.png'
  font:
    text: Helvetica Neue
    code: Consolas

copyright: Copyright &copy; 2018, 2022 Delphix Corp.

#google_analytics:
#  - 'UA-35429885-3'
#  - 'auto'

extra:
  social:
    - icon: fontawesome/solid/sitemap
      link: https://www.delphix.com/
    - icon: fontawesome/brands/facebook-f
      link: https://www.facebook.com/DelphixCorp/
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/delphix
    - icon: fontawesome/brands/linkedin-in
      link: https://www.linkedin.com/company/delphix
    - icon: fontawesome/brands/github
      link: https://github.com/delphix


markdown_extensions:
  - smarty
  - toc
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - attr_list
extra_css:
  - stylesheets/extra.css
  - stylesheets/delphix-brand.css

plugins:
  - mike:
      version_selector: true   # set to false to leave out the version selector
      css_dir: css             # the directory to put the version selector's CSS
      javascript_dir: js       # the directory to put the version selector's JS
      canonical_version: null  # the version for <link rel="canonical">; `null`
  - search
  - awesome-pages

extra:
  version:
    provider: mike
